name: Full CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    # - name: Run frontend tests
    #   run: |
    #     cd frontend
    #     npm test

  backend:
    runs-on: ubuntu-latest
    needs: frontend

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
    - name: Run backend tests
      run: |
        cd backend
        npm test
